### ISSUE TITLE
Have ithemCall Work By Calling Outlet(data) Instead of ithemCall(“Outlet”, data)

### ISSUE THREAD

**Issue by KabirSuri** [echo-lab/iThem#3]
By changing _ithemCall("Outlet", data)_ to _Outlet(data_), the outlet itself will act as a function and this will lead to more straightforward code in shorter text. For example, if the name of the outlet was emailMe, it would be more intuitive to type _emailMe("data")_ than _ithemCall("emailMe", data)_.

**Comment by panavrin** [comment]
That's an interesting idea. However, that's kind of risky as well because then one needs to take extra care with outlet name, and we have to check if they are using a valid name. For example, they can not use outlet names that have conflict with javascript native functions 

https://www.tutorialspoint.com/javascript/javascript_builtin_functions.htm

so I would keep it as is unless you have a stronger argument. If you agree, pleas close this issue.
